Master review
scanhex/zxc pull request #1
Opened 2020-03-04 20:00 UTC by salkaevruslan

2020-03-04 22:26 UTC, Geckostya reviewed
В целом код не связанный с графикой понравился. Связанный с графикой я пока особо не посмотрел

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Buff.h
> +    int index;
Не очень ООП стиль, просто допустить ошибки с индексами. Хотя бы сделайте enum, и лучше стараться поменьше завязывать логику работы на индексах

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Hero.cpp
> +    assert(gold >= 0 && "Wrong new gold!");
Лучше сделать uint gold, чтобы не было таких проверок, а также поставить в cmake флажки с варнингами на неявные касты.
Также и в других местах, где значения не должны быть отрицательными. Либо делать clamp(value, 0, MAX_VALUE)

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Hero.cpp
> +Hero::Hero(int damage, int attackRange, int moveSpeed, int attackSpeed, int maxHP,
Столько аргументов у класса - это немного писец.
Совсем красивым решением было бы выделить подобные характеристики в отдельный класс Stats или типо того, сделать класс StatsBuilder. Чтобы собрать характеристики писать такой код:
`StatBuilder().setDamage(34).setAttackRange(35).setMaxHP(50).create()`
Подобный подход позволяет контролировать и обрабатывать семантику при заполнении переменных, например, контролировать их диапозон, либо сложные формулы заполнения.
Также это хорошо по принципу уменьшения ответственности и класса Hero, и класса Stats. Это уменьшает сложность классов, упрощает рефакторинг, упрощает тестирование.
Плюс можно задавать дефолтные значения для переменных. Также, если таких дефолтных значений несколько, то можно сделать так:
`heroStatsBuilder = new StatsBuilder().set....`
`mobStatsBuilder = new StatsBuilder().set....`
и потом вызывать от них `.create()`

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Hero.h
> +    [[nodiscard]] int getGold() const;
Прикольная штука [[nodiscard]], не видел такого раньше :)

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Unit.cpp
> +Unit::Unit(int damage, int attackRange, int moveSpeed, int attackSpeed, int maxHP,
Вынесение всех этих параметров в отдельный класс избавит от их прописывания в каждом наследнике

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Unit.cpp
> +            }
Намешана в кучу логика слота и предмета, это путает, лучше подобные понятия разделять

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Unit.cpp
> +        item = Item();
А тут не будет утечек памяти? (p.s. сам не помню семантику выделения объектов в массиве)

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Unit.cpp
> +    std::swap(buffs_, newBuffs);
Это удаляет все баффы, может захотеться удалить только конкретные, например, по истечению времени. Логика кажется недоработанной. Можно пока не исправлять, пока не понадобится в реальном использовании, но иметь ввиду
Мне ещё лично не нравится выделение памяти на каждый чих, но это мелочи, можно не исправлять

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Unit.cpp
> +    double multiplier = 1 - ((0.052 * armor_) / (0.9 + 0.048 * std::abs(armor_)));
Интересно, откуда такие хитрые формулы?)

2020-03-04 22:26 UTC, Geckostya commented on src/UnitDrawable.h
> +                        { 5.0f, 5.0f, 7.0f }))
Не думаю, что эти параметры надо выставлять каждый раз при рендере. В любом случае стоит иметь место для редактирования подобных параметров шейдера вне функции draw, которая должна иметь максимальную производительность

2020-03-04 22:26 UTC, Geckostya commented on src/UnitDrawable.h
> +    const Unit& _unit;
drawable, который владеет юнитом, (а не наоборот, юнит, который владеет drawable) хоть и звучит контр-интуитивно, но кажется довольно практичным решением. Надо будет потом лучше об этом подумать, но пока респект)

2020-03-04 22:26 UTC, Geckostya commented on src/zxc.cpp
> +class ZxcApplication : public Platform::Application {
Разбей этот файл на несколько, пожалуйста, читать очень больно. Потом посмотрю их тогда

2020-03-04 22:26 UTC, Geckostya commented on README.md
> +Надо установить SDL2 (brew install sdl2 или sudo apt install libsdl2-dev или на Windows скачать https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz и распаковать в папку с проектом)
Цель на очень отдаленное будущее - сделать сборку полностью автоматической

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Hero.h
> +    void incrLevel();
Если эта функция в будущем будет делать что-то умнее, чем изменять уровень на единичку, то стоит дать ей более понятное название. Иначе норм

2020-03-04 22:26 UTC, Geckostya commented on src/Game/Point.h
> +    [[nodiscard]] bool xInRange(double left, double right) const;
У меня есть стойкое чувство, что если эти функции и понадобятся, то будут идти в паре. А вообще всякую математику можно реализовывать по мере необходимости. Заранее трудно понять, что понадобится, а что нет

2020-03-06 10:17 UTC, chimbersaw commented on src/Game/Unit.cpp
> +    double multiplier = 1 - ((0.052 * armor_) / (0.9 + 0.048 * std::abs(armor_)));
Эмпирически вывел

2020-03-07 21:53 UTC, Geckostya commented
Советую rebase использовать вместо merge remote

2020-03-08 13:31 UTC, Geckostya requested changes
Посмотрел графику

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +class ZxcApplication : public Platform::Application {
Это, вроде, можно вынеси в .hpp

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +	SceneGraph::Camera3D* _camera = nullptr;
Избегайте сырых указателей в подобных проектах.  Суровые Product Developerы используют shared_ptr.
Хотя в данном проекте можете и подзабить, но рекомендую. Течь всё будет - буду ругаться)

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +void ZxcApplication::loadModels() {
Это можно, вроде, вынести в отдельный класс \ файл, который будет заниматься загрузкой моделей

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +    new UnitDrawable(*_unitObjects.back(), _drawables, _units.back());
Создание объекта в пустоту выглядит так себе

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +		.setProjectionMatrix(Matrix4::perspectiveProjection(35.0_degf, 1.0f, 0.01f, 1000.0f))
aspect = 1.0f
Если перед первым же кадром не вызывается всегда viewportEvent, то стоит сменить на реальный aspect окна, иначе потом глюки будут, когда захотите поменять размеры окна по умолчанию

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +    return _cameraObject.absoluteTransformation().translation() + ray_world * dist;
три раза используется оно и то же значение позиции камеры, можно вынести в переменную

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +Vector3 ZxcApplication::intersectWithPlane(const Vector2i& windowPosition, const Vector3& planeNormal) const {
Лучше разнести на два метода: построение вектора по точке на экране и построение пересечения, с учетом того, что мы можем не пересечь плоскость

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +    Matrix4 viewMatrix = Matrix4::translation(_cameraObject.absoluteTransformation().translation());
viewMatrix = _camera->cameraMatrix()

2020-03-08 13:31 UTC, Geckostya commented on src/zxc.cpp
> +	_manipulator.rotate(Math::angle(_previousPosition, currentPosition), axis.normalized());
Лучше крутить _cameraObject, чтобы было понятнее, что происходит. Вместе с ним будет сразу поворачиваться и cameraMatrix

2020-03-10 08:55 UTC, chimbersaw commented on src/Game/Unit.cpp
> +        item = Item();
Не будет.
Если Item будет нетривиальным классом, то вместе с деструктором напишу оператор= с верным очищением памяти.

2020-03-10 08:57 UTC, chimbersaw commented on src/Game/Point.h
> +    [[nodiscard]] bool xInRange(double left, double right) const;
Я Point из лабы скопировал просто, если в будущем не нужно будет -- удалю.

2020-03-11 10:26 UTC, scanhex commented on src/zxc.cpp
> +    return _cameraObject.absoluteTransformation().translation() + ray_world * dist;
это да, просто много код менял, пока пытался заставить работать функцию

2020-03-11 10:29 UTC, scanhex commented on src/zxc.cpp
> +Vector3 ZxcApplication::intersectWithPlane(const Vector2i& windowPosition, const Vector3& planeNormal) const {
В целом да, но нам вроде как только эта функциональность и нужна, при этом угол камеры никогда параллельным плоскости быть не должен, как и отвернутой от нее камера быть не должна. Вообще, нам с лихвой хватит камеры, которая смотрит под фиксированным углом и движется в плоскости параллельной нашей.

2020-03-11 10:30 UTC, scanhex commented on src/zxc.cpp
> +	SceneGraph::Camera3D* _camera = nullptr;
Надо бы сделать, но так, опять же, делают в документации... У нас просто работы с указателями как таковой вообще пока нет, тут, как я понял, это нужно просто чтобы nullptr поставить изначально. Тогда уж какой-нибудь optional лучше, видимо

2020-03-11 10:30 UTC, scanhex commented on src/zxc.cpp
> +    new UnitDrawable(*_unitObjects.back(), _drawables, _units.back());
Согласен, но так везде написано в документации, я так понимаю, эта DrawablesGroup, в которую мы кладем наш объект, сама память очистит, но надо будет разобраться, может они просто для простоты так делают

2020-03-11 10:31 UTC, scanhex commented on src/zxc.cpp
> +    Matrix4 viewMatrix = Matrix4::translation(_cameraObject.absoluteTransformation().translation());
Ага, обсудили.

2020-03-11 10:31 UTC, scanhex commented on src/zxc.cpp
> +	_manipulator.rotate(Math::angle(_previousPosition, currentPosition), axis.normalized());
Обсудили.

2020-04-03 10:38 UTC, salkaevruslan commented on src/Game/GameState.h
> +    void damage(double amount, Player player);
Не понятно, player-- тот кто наносит урон или кому наносят урон.

2020-04-03 16:10 UTC, scanhex commented
чисто misprint

2020-04-03 22:25 UTC, closed without merging